DROP TABLE tp.puerto;
DROP TABLE tp.centro;
DROP TABLE tp.sucursal;
DROP TABLE tp.ruta;
DROP TABLE tp.stock;
DROP TABLE tp.cantidad;
DROP TABLE tp.orden_provision;
DROP TABLE tp.producto;
DROP TABLE tp.centro_logistico;